#!/bin/bash
apt-get install vim

if [ ! -f  /home/fsmith/.vimrc ]
then
   echo "set nu" >/home/fsmith/.vimrc
   echo "set mu" >>/home/fsmith/.vimrc
   echo "syntax on" >>/home/fsmith/.vimrc
fi

apt-get install git -y 
git config --global user.name "Frank Smith" 
git config --global user.email fsmith@cavium.com
git config --global core.editor vim
git config --global --add color.ui true
git config --global format.pretty oneline


apt-get install openssl
apt-get install ssh
apt-get install sshd-server
apt-get install ntp
apt-get install net-tools
apt-get install tcpdump
apt-get install ethtool
apt-get install nds-client
apt-get install cscope

apt-get install tftpd-hpa  -y 
apt-get install alien -y 
apt-get install gdisk -y
apt-get install gparted -y
apt-get install ipsec-tools -y
apt-get install nfs-client -y
apt-get install xz-utils -y   
apt-get install libncurses-dev -y
apt-get install fakeroot -y
apt-get install build-essential -y

apt-get build-dep linux-image-$(uname -r) -y
apt-get install linux-headers-`uname -r` -y
apt-get install kernel-package -y






