#!/bin/bash
#
#   Assume the directory structure looks like this
#
#     <BASE_DIR>                    <REV DIR>       <OUTPUT_DIR>
#  /home/fsmith/marvell   /sdk   /SDK-19.06.3-src
#                         /sdk   /SDK-19.06.3-src  /cn96xx-release-output
#                              
#                         /dpdk  /dpdk-19.05
#                         /dpdk  /fs_target
#                         /libpcap
#                         /numa
#                         /ubuntu
#

DPDK_REV=dpdk-19.05

DEVICE=cn96xx

if [ "$DEVICE" ==  "cn96xx" ] ; then

    OUTPUT_DIR=cn96xx-release-output

    BASE_DIR=/home/fsmith/marvell

# because the engineering developement has a different path structure
    SDK_REV=sdk10_ed1003_with_dpdk/SDK10.0-ED1003-DPDK/sdk

else

   OUTPUT_DIR=cn83xx-release-output

   BASE_DIR=/sdk

   SDK_REV=SDK10.0_19.06.3-src

fi

SDK_DIR=$BASE_DIR/sdk/$SDK_REV
DPDK_DIR=$BASE_DIR/dpdk/$DPDK_REV

export RTE_KERNELDIR=$SDK_DIR/$OUTPUT_DIR/build/linux-custom
export PATH=$SDK_DIR/toolchain/marvell-tools-233.0/bin:$PATH
export CROSS=aarch64-marvell-linux-gnu-

export DESTDIR=$BASE_DIR/dpdk/fs_target
export RTE_SDK=$BASE_DIR/dpdk/$DPDK_REV
export RTE_ARCH=arm64
export RTE_TARGET=build          

export LD_LIBRARY_PATH=$BASE_DIR/sdk/$SDK_REV/toolchain/marvell-tools-233.0/lib64:${LD_LIBRARY_PATH}          
echo "OUTPUT_DIR:  $OUTPUT_DIR"
echo "SDK_DIR: $SDK_DIR"
echo "RTE_KERNELDIR: $RTE_KERNELDIR"
echo "LD_LIBRARY_PATH: $LD_LIBRARY_PATH"
echo ""
echo "make install T=arm64-thunderx2-linux-gcc"

