#!/bin/bash
banner() {
echo "*****************************************"
echo "*  $1"
echo "*****************************************"
}

TARGET=cn83xx
#TARGET=cn91xx
#TARGET=cn96xx_CRB

#PROGRAM_NAME=dpdk-devbind.py
PROGRAM_NAME=dpdk-devbind


if [ "$TARGET" == "cn83xx" ] ; then 


echo 24 > /sys/bus/pci/devices/0000\:04\:00.0/sriov_numvfs

/usr/share/dpdk/usertools/dpdk-devbind.py -u 0001:01:00.5 0001:01:00.6
/usr/share/dpdk/usertools/dpdk-devbind.py -b vfio-pci 0001:01:00.5 0001:01:00.6

# bind non physical interfaces to have 48 queues which is required by more than 8 cores
/usr/share/dpdk/usertools/dpdk-devbind.py -u 0001:01:01.3 0001:01:01.4 0001:01:01.5 0001:01:01.6
/usr/share/dpdk/usertools/dpdk-devbind.py -b vfio-pci 0001:01:01.3 0001:01:01.4 0001:01:01.5 0001:01:01.6


elif  [ "$TARGET" == "cn91xx" ] ; then

 banner "show interfaces we are interested in .."
 $PROGRAM_NAME  --status | grep  0001:01:00\.[12] 

 banner " unbinding 0001:01:00.1"
 $PROGRAM_NAME  -u 0001:01:00.1 
 banner " unbinding 0001:01:00.2"
 $PROGRAM_NAME  -u 0001:01:00.2 


 banner " bind  0001:01:00.1 to dpdk driver"
 $PROGRAM_NAME  --bind=vfio-pci   0001:01:00.1 
 banner " bind  0001:01:00.2 to dpdk driver"
 $PROGRAM_NAME  --bind=vfio-pci   0001:01:00.2 

elif  [ "$TARGET" == "cn96xx_CRB" ] ; then

  banner "show interfaces we are interested in .."
  $PROGRAM_NAME  --status | grep  0002:0[467]:00\.0

#  banner "  unbinding 0002:02:00.0"
#  $PROGRAM_NAME    -u 0002:02:00.0
#  banner "  unbinding 0002:03:00.0"
#  $PROGRAM_NAME    -u 0002:03:00.0
  banner "  unbinding 0002:04:00.0"
  $PROGRAM_NAME    -u 0002:04:00.0
#  banner "  unbinding 0002:05:00.0"
#  $PROGRAM_NAME    -u 0002:05:00.0
  banner "  unbinding 0002:06:00.0"
  $PROGRAM_NAME    -u 0002:06:00.0
  banner "  unbinding 0002:07:00.0"
  $PROGRAM_NAME    -u 0002:07:00.0
#  banner "  unbinding 0002:08:00.0"
#  $PROGRAM_NAME    -u 0002:08:00.0
#  banner "  unbinding 0002:09:00.0"
#  $PROGRAM_NAME    -u 0002:09:00.0
 


#  banner " bind  0002:02:00.0 to dpdk driver"
#  $PROGRAM_NAME  --bind=vfio-pci   0002:02:00.0
#  banner " bind  0002:03:00.0 to dpdk driver"
#  $PROGRAM_NAME  --bind=vfio-pci   0002:03:00.0
  banner " bind  0002:04:00.0 to dpdk driver"
  $PROGRAM_NAME  --bind=vfio-pci   0002:04:00.0
#  banner " bind  0002:05:00.0 to dpdk driver"
#  $PROGRAM_NAME  --bind=vfio-pci   0002:05:00.0
  banner " bind  0002:06:00.0 to dpdk driver"
  $PROGRAM_NAME  --bind=vfio-pci   0002:06:00.0
  banner " bind  0002:07:00.0 to dpdk driver"
  $PROGRAM_NAME  --bind=vfio-pci   0002:07:00.0
#  banner " bind  0002:08:00.0 to dpdk driver"
#  $PROGRAM_NAME  --bind=vfio-pci   0002:08:00.0
#  banner " bind  0002:09:00.0 to dpdk driver"
#  $PROGRAM_NAME  --bind=vfio-pci   0002:09:00.0




else
 echo "unrecongize target device: $TARGET"


fi

 banner " Print $PROGRAM_NAME --status"
#$PROGRAM_NAME  --status | grep  0001:01:00\.[12] 
#$PROGRAM_NAME  --status  
