#!/bin/bash

echo "export ARCH=arm64"
export ARCH=arm64

echo "export CROSS=/sdk/sdk/SDK-10.1.1.0/toolchain/marvell-tools-238.0/bin/aarch64-marvell-linux-gnu-"
      export CROSS=/sdk/sdk/SDK-10.1.1.0/toolchain/marvell-tools-238.0/bin/aarch64-marvell-linux-gnu-


echo "export RTE_KERNELDIR=/home/fsmith/marvell/sdk/SDK-10.1.1.0/cn96xx-release-output/build/linux-custom/"
      export RTE_KERNELDIR=/home/fsmith/marvell/sdk/SDK-10.1.1.0/cn96xx-release-output/build/linux-custom/

echo "export RTE_SDK=$PWD"
      export RTE_SDK=$PWD

echo  "export RTE_TARGET=build"
       export RTE_TARGET=build

echo "   "
echo " Create a .config file...  "
echo "   from the <RTE_SDK> directory, run:  "
echo "  1)  make config T=arm64-thunderx-linuxapp-gcc"

echo "   "
echo " Modify the  .config file...  "
echo "   "
echo "  2) Remove libpcap  dependency ..."
echo "       sed -ri 's,(PMD_PCAP=).*,\1y,' build/.config "
echo "   "
echo "  3) Remove \"NUMA\"  dependency ..."
echo "       Edit the <DPDK_BASE>/build/.compile file "
echo "       Comment out lines with : "
echo "          CONFIG_RTE_MAX_NUMA_NODES"
echo "          RTE_LIBRTE_VHOST_NUMA"
echo "          CONFIG_RTE_LIBRTE_VHOST_NUMA"
echo "   "

